# Generated by Django 4.0 on 2022-01-07 18:16

from django.db import migrations, models
import uy.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=uy.helpers.UploadTo('profile')),
        ),
    ]
