# Generated by Django 4.0 on 2022-01-07 18:16

from django.db import migrations, models
import django.db.models.deletion
import uy.helpers
import uy.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0003_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=uy.helpers.UploadTo('category'))),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'kategoriyalar',
            },
            bases=(uy.mixins.TranslateMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='izoh')),
                ('file', models.FileField(upload_to=uy.helpers.UploadTo('post'), verbose_name='Rasm/Video')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='kategoriya')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='client.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to=uy.helpers.UploadTo('comment'))),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='client.user')),
            ],
        ),
    ]
